dictionnary/urls.py
from django.urls import path
from dictionnary import views

app_name = 'dictionnary'

urlpatterns = [
    path('', views.WordListView.as_view(), name='listword'),
    path('detailword/<int:pk>', views.WordDetailView.as_view(), name='detailword'),
    path('searchword/', views.search_word,name='searchword'),
    path('generator/', views.generator_form_view, name='setgenerator'),
]

home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about/', views.about_view, name='about'),
    path('mentions-legales/', views.mentions_legales, name='mentions_legales'),
]

dictionnary/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now

class Word(models.Model):
    morwuwhw = models.CharField(null=False,blank=False,max_length=50)
    french = models.CharField(null=False,blank=False,max_length=50)
    precisions = models.TextField(null=False,blank=True)
    entry_date = models.DateField(default=now)

    def __str__(self):
        return self.french + " : " + self.morwuwhw + " (" + self.precisions[0:10] + ")"

    def get_absolute_url(self):
        return reverse("dictionnary:createword",kwargs={})

dictionnary/forms.py
from django import forms
from django.core.validators import RegexValidator

class SearchWordForm(forms.Form):
    FRANCAIS = 'FR'
    MORWUWHW = 'MH'
    LANGUAGES = (
        (FRANCAIS, 'Français'),
        (MORWUWHW, 'Morwuwhw'),
    )

    alphanumeric = RegexValidator(
        regex=r'^[a-zàáâãäåòóôõöèéêëçìíîïùúûüÿ]*$',
        message='Votre mot ne doit contenir que des lettres minuscules'
    )

    word = forms.CharField(max_length=50,validators=[alphanumeric])
    language = forms.ChoiceField(choices=LANGUAGES)

class GeneratorForm(forms.Form):
    max_words = forms.IntegerField(min_value=1,max_value=100)
    size_words = forms.IntegerField(min_value=1,max_value=40)

dictionnary/views.py
import logging
import csv

from django.shortcuts import render
from django.http import Http404
from django.utils.translation import ugettext as _
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from dictionnary.models import Word
from dictionnary.forms import SearchWordForm, GeneratorForm
from dictionnary import matrix as mx
from dictionnary import generator as gen

logging.basicConfig(level=logging.DEBUG)
_logger = logging.getLogger(__name__)

class FormListView(FormMixin, ListView):
    def get(self, request, *args, **kwargs):
        # From ProcessFormMixin
        form_class = self.get_form_class()
        self.form = self.get_form(form_class)

        # From BaseListView
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty and len(self.object_list) == 0:
            raise Http404(_(u"Empty list and '%(class_name)s.allow_empty' is False.")
                          % {'class_name': self.__class__.__name__})

        context = self.get_context_data(object_list=self.object_list, form=self.form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class WordListView(FormListView):
    form_class = SearchWordForm
    model = Word
    template_name = 'dictionnary/word_list_view.html'
    queryset = Word.objects.all().order_by('morwuwhw')
    paginate_by = 20

    def load_file_data(self):
        with open('../saved_data/words-data.csv') as f:
                reader = csv.reader(f)

                for row in reader:
                    _logger.debug("french: {}, morwuwhw: {}, description: {}".format(row[0],row[1],row[2]))
                    _, created = Word.objects.get_or_create(
                        french=row[0],
                        morwuwhw=row[1],
                        description=row[2],
                        )
                    # creates a tuple of the new object or
                    # current object and a boolean of if it was created

    def get_context_data(self, **kwargs):
        context = super(WordListView, self).get_context_data()
        context['word_count'] = Word.objects.count()
        return context


class WordDetailView(DetailView):
    model = Word
    template_name = 'dictionnary/word_detail_view.html'


def search_word(request):
    search_form = SearchWordForm()

    if request.method == 'POST':
        search_form = SearchWordForm(request.POST)

        if search_form.is_valid():
            result = None
            if search_form.cleaned_data['language'] == SearchWordForm.MORWUWHW:
                result = Word.objects.filter(morwuwhw=search_form.cleaned_data['word']).order_by('morwuwhw')
            elif search_form.cleaned_data['language'] == SearchWordForm.FRANCAIS:
                result = Word.objects.filter(french=search_form.cleaned_data['word']).order_by('french')
            else:
                return render(request,'dictionnary/word_list_view.html')

            if len(result) == 0:
                if search_form.cleaned_data['language'] == SearchWordForm.MORWUWHW:
                    result = Word.objects.filter(morwuwhw__icontains=search_form.cleaned_data['word']).order_by('morwuwhw')
                elif search_form.cleaned_data['language'] == SearchWordForm.FRANCAIS:
                    result = Word.objects.filter(french__icontains=search_form.cleaned_data['word']).order_by('french')
                else:
                    return render(request,'dictionnary/word_list_view.html')

            return render(request,'dictionnary/search_result.html',{'word_list':result})
        else:
            return render(request,'dictionnary/word_list_view.html')

def generator_form_view(request):
    form = GeneratorForm()

    if request.method == 'POST':
        form = GeneratorForm(request.POST)

        if form.is_valid():
            examples_words = Word.objects.values_list('morwuwhw')
            words = []
            for word in examples_words:
                words.append(word[0])
            matrix = mx.generate_matrix(words)
            gen_words = gen.generate_words(
                max_mots=form.cleaned_data['max_words'],
                word_size=form.cleaned_data['size_words'],
                p=matrix,
                in_database_words=words
            )
            return render(request,'dictionnary/generator_form.html',{'gen_words':gen_words})
    return render(request,'dictionnary/generator_form.html',{'form':form})

dictionnary/templates/dictionnary/generator_form.html
{% extends "base.html" %}

{% block title %}
  <title>LSV – Morwuwhw word generator</title>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Générer">
  </form>
  {% if gen_words %}
  <p>Une liste de {{ gen_words|length }} mots a été générées.</p>
  <table>
    <tr class="tab-header">
      <th>Mot</th>
    </tr>
    {% for word in gen_words %}
    <tr class="tab-rows">
      <th>{{ word }}</th>
    </tr>
    {% endfor %}
  </table>
  {% endif %}
{% endblock %}

dictionnary/templates/dictionnary/search_result.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>LSV – Dictionnary Search Result</title>
{% endblock %}

{% block additional_css %}
  <link rel="stylesheet" href="{% static 'css/table-style.css' %}">
{% endblock %}

{% block content %}
  <p>Votre recherche à donner {{ word_list|length }} résultats.</p>
  <div class="container btn btn-primary">
    <a href="{% url 'dictionnary:listword' %}">Retour</a>
  </div>
  <table>
    <tr class="tab-header">
      <th>Français</th>
      <th>Morwuwhw</th>
      <th>Précisions</th>
    </tr>
    {% for word in word_list %}
    <tr class="tab-rows">
      <td><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.french }}</a></td>
      <td><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.morwuwhw }}</a></td>
      <td>{{ word.precisions }}</td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

dictionnary/templates/dictionnary/word_detail_view.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>LSV – Dictionnary {{ word.morwuwhw }}</title>
{% endblock %}

{% block additional_css %}
  <link rel="stylesheet" href="{% static 'css/table-style.css' %}">
{% endblock %}

{% block content %}
<table>
  <tr class="tab-header">
    <th>Français</th>
    <th>Morwuwhw</th>
    <th>Précisions</th>
  </tr>
  <tr class="tab-row">
    <td class="word-cell">{{ word.french }}</td>
    <td class="word-cell">{{ word.morwuwhw }}</td>
    <td class="word-cell">{{ word.precisions }}</td>
  </tr>
</table>

<div class="container buttons">
  <a href="{% url 'dictionnary:listword' %}" class="btn btn-primary">Retour</a>
</div>
{% endblock %}

dictionnary/templates/dictionnary/word_list_view.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>LSV – Morwuwhw dictionnary</title>
{% endblock %}

{% block additional_css %}
<link rel="stylesheet" href="{% static 'css/table-style.css' %}">
<link rel="stylesheet" href="{% static 'css/search-style.css' %}">
{% endblock %}

{% block content %}
<p>Ci-dessous figure un dictionnaire linguistique Français-Morwuwhw.
<p>Mais qu’est-ce que le Morwuwhw ?</p>
<p>Il s’agit d’une langue de mon invention, afin d’étoffer un l’univers d’une histoire qui me trotte dans la tête.</p>
<p>Le dictionnaire contient actuellement {{ word_count }} mots.</p>
<div class="container buttons">
	<div class="row">
		<div class="col-sm-6">
			<form class="search-form" method="post" action="{% url 'dictionnary:searchword' %}">
				{% csrf_token %}
				{{ form.as_p }}
				<input class="btn btn-primary" type="submit" value="Chercher">
			</form>
		</div>
	</div>
</div>
<table>
	<tr class="tab-header">
		<th>Français</th>
		<th>Morwuwhw</th>
		<th>Précisions</th>
	</tr>
	{% for word in word_list %}
	<tr class="tab-row">
		<td class="word-cell hover-highlight"><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.french }}</a></td>
		<td class="word-cell hover-highlight"><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.morwuwhw }}</a></td>
		<td>{{ word.precisions }}</td>
	</tr>
	{% endfor %}
</table>

<div class="pagination">
	<span class="step-links">
		{% if page_obj.has_previous %}
		<a href="?page=1">&laquo; first</a>
		<a href="?page={{ page_obj.previous_page_number }}">previous</a>
		{% endif %}

		<span class="current">
			Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
		</span>

		{% if page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number }}">next</a>
		<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
		{% endif %}
	</span>
</div>
{% endblock %}