dictionnary/urls.py
from django.urls import path
from dictionnary import views

app_name = 'dictionnary'

urlpatterns = [
    path('', views.WordListView.as_view(), name='listword'),
    path('detailword/<int:pk>', views.WordDetailView.as_view(), name='detailword'),
    path('searchword/', views.search_word,name='searchword'),
    path('generator/', views.generator_form_view, name='setgenerator'),
]

home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about/', views.about_view, name='about'),
    path('mentions-legales/', views.mentions_legales, name='mentions_legales'),
]

novlog/urls.py
from django.urls import path
from novlog import views

app_name = 'novlog'

urlpatterns = [
    path('', views.NovelListView.as_view(), name='listnovels'),
]

rollchat/urls.py
from django.urls import path

from . import views

app_name = 'rollchat'

urlpatterns = [
    path('', views.RollchatRoomListView.as_view(), name='index'),
    path('rooms/<slug:slug>/', views.RollchatRoomDetailView.as_view(), name='room'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	{% block title %}
	<title>LSV</title>
	{% endblock %}

	<link rel="stylesheet" href="{% static 'bulma/css/bulma.min.css' %}">
	<link rel="stylesheet" href="{% static 'fork-awesome/css/fork-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/base-style.css' %}">

	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>

	{% block additional_css %}
	{% endblock %}

  {% block top_additional_js %}
  {% endblock %}
</head>

<body>
	<section class="section">
		<div class="container">
			<header>
				<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
					<div class="navbar-brand">
						<a class="navbar-item" href="{% url 'home:home' %}">
							<p>LSV</p>
						</a>
					</div>

					<a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="lsv-navbar">
						Menu
					</a>

					<div id="lsv-navbar" class="navbar-menu">
						<div class="navbar-end">
							<a class="navbar-item" href="{% url 'home:about' %}">À PROPOS</a></li>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">ÉCRITURE</a>
                <div class="navbar-dropdown">
                  <a class="navbar-item" href="{% url 'novlog:listnovels' %}">NOVLOG</a>
                  <a class="navbar-item" href="{% url 'dictionnary:listword' %}">DICTIONNAIRE</a>
                </div>
              </div>
              <div class="navbar-item has-dropdown is-hoverable">
								<a class="navbar-link">AUTRE</a>
								<div class="navbar-dropdown">
                  <a class="navbar-item" href="{% url 'rollchat:index' %}">JDR ROOMS</a>
                  <hr class="navbar-divider">
									{% if user.is_authenticated %}
  									<a class="navbar-item" href="{% url 'logout' %}">LOG OUT</a>
									{% else %}
  									<a class="navbar-item" href="{% url 'login' %}">LOG IN</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				</nav>
			</header>
		</div>
	</section>

	<section class="banner">
		<div id="div-banner">
			{% block banner %}
			{% endblock %}
		</div>
	</section>

	<section class="section">
		<div class="container">
			<div id="main">
				{% block content %}
				{% endblock %}
			</div>

			<footer id="site-footer">
        <div class="columns">
          <div class="column">
            <p>@Copyleft <a href="{% url 'home:about' %}">Redmood</a></p>
            <a href="{% url 'home:mentions_legales' %}">Mentions légales</a>
            <p>Unless specified differently, all this site code and content is licensed
              under <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.fr">CC-BY-SA
                4.0</a>.</p>
          </div>
          <div class="column">
            <div class="ressoc">
              <p>Vous pouvez me retrouver sur les réseaux libres :
                <ul class="ressoc">
                  <li class="ressoc mastodon">
                    <a href="https://mamot.fr/@redmood">
                      <span class="fa fa-mastodon fa-3x"></span>
                      <br>
                      <p>Mastodon</p>
                    </a>
                  </li>
                  <li class="ressoc gitlab">
                    <a href="https://framagit.org/redmood">
                      <span class="fa fa-gitlab fa-3x"></span>
                      <br>
                      <p>Framagit</p>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
        </div>
			</footer>
		</div>
	</section>
  {% block bottom_additional_js %}
  {% endblock %}
</body>

</html>