home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about/', views.about_view, name='about'),
    path('mentions-legales/', views.mentions_legales, name='mentions_legales'),
]

rollchat/urls.py
from django.urls import path

from . import views

app_name = 'rollchat'

urlpatterns = [
    path('', views.RollchatRoomListView.as_view(), name='index'),
    path('rooms/<slug:slug>/', views.RollchatRoomDetailView.as_view(), name='room'),
]

rollchat/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


class RollchatRoom(models.Model):
    slug = models.SlugField(max_length=150)
    max_players = models.PositiveSmallIntegerField(default=6)
    room_admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owns_rooms')
    room_master = models.ForeignKey(User, on_delete=models.CASCADE, related_name='masters_rooms', null=True, blank=True)
    room_members = models.ManyToManyField(User, related_name='in_rooms', blank=True)

    def add_user(self, user):
        self.room_members.add(user)

    def remove_user(self, user):
        self.room_members.remove(user)

    def __str__(self):
        return f'{self.slug}'


class ChatRoomHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_messages')
    room = models.ForeignKey(RollchatRoom, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField(null=True, blank=True)
    sent_on = models.DateTimeField(null=False, blank=False, default=now)

rollchat/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.urls import reverse_lazy
from django.db.models import Q

from rollchat.models import RollchatRoom


class RollchatRoomListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = RollchatRoom
    template_name = 'rollchat/chat-index.html'

    def get_queryset(self):
        queryset = RollchatRoom.objects.all()

        if self.request.user.is_superuser:
            return queryset

        user = self.request.user
        user_rooms = user.owns_rooms.all().values_list('id', flat=True)
        user_rooms |= user.masters_rooms.all().values_list('id', flat=True)
        user_rooms |= user.in_rooms.all().values_list('id', flat=True)
        return queryset.filter(id__in=user_rooms)


class RollchatRoomDetailView(LoginRequiredMixin, DetailView):
    model = RollchatRoom
    template_name = 'rollchat/chat-room.html'

    def get_context_data(self, **kwargs):
        context = super(RollchatRoomDetailView, self).get_context_data(**kwargs)
        context['room_name'] = self.kwargs['slug']
        context['username'] = self.request.user.username
        return context

rollchat/templates/rollchat/chat-index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>LSV – Rollchat Salon</title>
{% endblock %}

{% block content %}
  <p>Choisissez votre room :</p>
  <table>
    <tr class="tab-header">
      <th>Room</th>
      <th></th>
    </tr>
    {% for room in object_list %}
      <tr class="tab-row">
        <td>{{ room.slug }}</td>
        <td>
          <a class="button" href="{% url 'rollchat:room' slug=room.slug %}">Join</a>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

rollchat/templates/rollchat/chat-room.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  <title>LSV – Rollchat Room {{ room_name }}</title>
{% endblock %}

{% block additional_css %}
  <link rel="stylesheet" href="{% static 'rollchat/css/rollchat.css' %}">
{% endblock %}

{% block content %}
  <h1 class="room-welcome">Bienvenue <span id="user_name" class="username">{{ username }}</span>, tu es dans la room : <span id='room-name'>{{ room_name }}</span></h1>
  <div class="columns">
    <div class="column is-two-thirds">
      <div class="chatbox" id="chat-log">
        <table>
        </table>
      </div><br>
      <textarea id="chat-message-input" type="text" placeholder="Écrivez votre message ici"></textarea><br>
      <input id="chat-message-submit" type="button" value="Envoyer">
    </div>
    <div class="column is-one-third">
      <div class="usersbox">
        <ul>
        </ul>
      </div>
      <p>Comment lancez un dé ? Par exemple : <br>
      <ul>
        <li>– Pour lancer un dé 20, écrivez : #d20</li>
        <li>– Pour lancer 3 dès 6, écrivez : #3d6</li>
      </ul>
      Enjoy !! :D
    </div>
  </div>
{% endblock %}

{% block bottom_additional_js %}
  <script type="text/javascript" src="{% static 'rollchat/js/reconnecting-websocket/reconnecting-websocket.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'rollchat/js/chat-room.js' %}"></script>
{% endblock %}